### ISSUE TITLE
Broken documentation

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/SonataDatagridBundle#9]
Hi,

Documentation of this bundle seems to be broken: http://sonata-project.org/bundles/datagrid

Can only see header and footer of your website, no content.

Thanks.

**Comment by Emirii** [comment]
Hi there, I had the same problem. I think they haven't made a page yet because the configuration is just this:

To begin, add the dependent bundles to the vendor/bundles directory. Add the following lines to the file deps:

    php composer.phar require sonata-project/datagrid-bundle

Now, add the bundle to the kernel:


    <?php

    // app/AppKernel.php

    public function registerbundles()
    {
        return array(
            // Vendor specifics bundles
            new Sonata\DatagridBundle\SonataDatagridBundle(),
        );
    }


There is no configuration for now ...

**Comment by Soullivaneuh** [comment]
ping @rande.

I don't really know how your documentation generation works.

**Comment by OskarStark** [comment]
still not rendered

**Comment by core23** [comment]
@rande Can you explain how the magic works?

**Comment by josensanchez** [comment]
Any chance to fix this sometime soon? Or at least share some example code on how to implement this datagrid

**Comment by rande** [comment]
Fixed but the documentation is quite empty.
